# in config/controllers.yaml
services:
  controller.default:
    lazy: true
    class: App\Controller\DefaultController
    arguments: [ "@request" ]
  controller.page:
    lazy: true
    class: App\Controller\PageController
    arguments: [ "@request"]
